<?php

namespace AppBundle\Repository;

/**
 * BalanceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BalanceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
