<?php

namespace AppBundle\Repository;

/**
 * ConsumptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumptionRepository extends \Doctrine\ORM\EntityRepository
{
}
