<?php

namespace AppBundle\Repository;

/**
 * ConsumptionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsumptionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
