<?php

namespace AppBundle\Repository;

/**
 * IncomeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
